Description: >
  Udacity Cloud DevOps Nanodegree/2020 - Marcos Antonio de Jesus Filho
  Deploy a High-Availability web app using CloudFormation
  Network infrasctructure

Parameters:
  
  EnvironmentName:
      Description: Environment Name that will be prefixed on the resources name.
      Type: String

  VPCCidr:
      Description: Enter the value of the VPC CIDR Block
      Type: String
      Default: 10.0.0.0/16

  PublicSubnet1Cidr:
      Description: Enter the IP range for this subnet.
      Type: String
      Default: 10.0.0.0/24

  PublicSubnet2Cidr:
      Description: Enter the IP range for this subnet.
      Type: String
      Default: 10.0.1.0/24
      
  PrivateSubnet1Cidr:
      Description: Enter the IP range for this subnet.
      Type: String
      Default: 10.0.2.0/24

  PrivateSubnet2Cidr:
      Description: Enter the IP range for this subnet.
      Type: String
      Default: 10.0.3.0/24

Resources:

  VPC:
      Type: AWS::EC2::VPC
      Properties: 
        CidrBlock: !Ref VPCCidr
        Tags: 
          - Key: Name
            Value: !Ref EnvironmentName

  InternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties: 
        Tags: 
          - Key: Name
            Value: !Ref EnvironmentName

  IGAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties: 
        InternetGatewayId: !Ref InternetGateway
        VpcId: !Ref VPC

  PublicSubnet1:
      Type: AWS::EC2::Subnet
      Properties: 
        AvailabilityZone: !Select [ 0, !GetAZs '']
        CidrBlock: !Ref PublicSubnet1Cidr
        MapPublicIpOnLaunch: True
        Tags: 
          - Key: Name
            Value: !Sub "${EnvironmentName}-Public Subnet 1"
        VpcId: !Ref VPC

  PublicSubnet2:
      Type: AWS::EC2::Subnet
      Properties: 
        AvailabilityZone: !Select [ 1, !GetAZs '']
        CidrBlock: !Ref PublicSubnet2Cidr
        MapPublicIpOnLaunch: True
        Tags: 
          - Key: Name
            Value: !Sub "${EnvironmentName}-Public Subnet 2"
        VpcId: !Ref VPC
        
  PrivateSubnet1:
      Type: AWS::EC2::Subnet
      Properties: 
        AvailabilityZone: !Select [ 0, !GetAZs '']
        CidrBlock: !Ref PrivateSubnet1Cidr
        Tags: 
          - Key: Name
            Value: !Sub "${EnvironmentName}-Private Subnet 1"
        VpcId: !Ref VPC

  PrivateSubnet2:
      Type: AWS::EC2::Subnet
      Properties: 
        AvailabilityZone: !Select [ 1, !GetAZs '']
        CidrBlock: !Ref PrivateSubnet2Cidr
        Tags: 
          - Key: Name
            Value: !Sub "${EnvironmentName}-Private Subnet 2"
        VpcId: !Ref VPC

  EIP1Allocation:
      Type: AWS::EC2::EIP
      DependsOn: IGAttachment
      Properties: 
        Domain: vpc
        Tags: 
          - Key: Name
            Value: !Sub "${EnvironmentName}-Elastic IP 1 Allocation"

  EIP2Allocation:
      Type: AWS::EC2::EIP
      DependsOn: IGAttachment
      Properties: 
        Domain: vpc
        Tags: 
          - Key: Name
            Value: !Sub "${EnvironmentName}-Elastic IP 2 Allocation"
