Description: >
  Udacity Cloud DevOps Nanodegree/2020 - Marcos Antonio de Jesus Filho
  Deploy a High-Availability web app using CloudFormation
  Servers infrasctructure

Parameters:

  EnvironmentName:
      Description: Environment name that will be prefixed to resources names and identifiers
      Type: String

Resources:

  LBSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties: 
        GroupDescription: Security Group for the Load Balancer
        GroupName: !Sub "${EnvironmentName}-LBSecurityGroup"
        SecurityGroupIngress: 
          - CidrIp: 0.0.0.0/0
            Description: HTTP Ingress Rule
            FromPort: 80
            IpProtocol: tcp
            ToPort: 80
          - CidrIp: 0.0.0.0/0
            Description: SSH Ingress Rule
            FromPort: 22
            IpProtocol: tcp
            ToPort: 22
        VpcId: 
          Fn::ImportValue:
            !Sub "${EnvironmentName}-VPCID"

  S3ReadOnlyEC2:
      Type: AWS::IAM::Role
      Properties: 
        AssumeRolePolicyDocument: 
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
              Action:
                - 'sts:AssumeRole' 
        Description: Allow EC2 Instances to Read S3 objects
        ManagedPolicyArns: 
          - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
        RoleName: UdacityS3ReadOnlyEC2

  ProfileWithRolesForOurApp:
      Type: AWS::IAM::InstanceProfile
      Properties: 
        Roles:
          - UdacityS3ReadOnlyEC2

  BastionHost:
      Type: AWS::EC2::Instance
      Properties: 
        BlockDeviceMappings: 
          - DeviceName: /dev/sdk
            Ebs:
              VolumeSize: 10
        IamInstanceProfile: !Ref ProfileWithRolesForOurApp
        ImageId: ami-003634241a8fcdec0
        InstanceInitiatedShutdownBehavior: stop
        InstanceType: t2.micro
        KeyName: jumpbox-us-west-2
        NetworkInterfaces: 
          - AssociatePublicIpAddress: true
            DeviceIndex: 0
            GroupSet: 
              - !Ref LBSecurityGroup
            SubnetId: 
              Fn::ImportValue:
                !Sub "${EnvironmentName}-PublicSubnet1ID"
        Tags: 
          - Key: Name
            Value: !Sub "${EnvironmentName}-BastionHost"
        UserData: 
          Fn::Base64: !Sub |
            #!/bin/bash
            apt-get update -y
            apt-get install unzip awscli -y
            apt-get install apache2 -y
            systemctl start apache2.service
            cd /var/www/html
            aws s3 cp s3://udacity-demo-1/udacity.zip .
            unzip -o udacity.zip
